---
- hosts: apache
  become: yes
  gather_facts: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install apache2-2
      package: name=nginx update_cache=yes state=latest
    - name: install apache2-2
      yum: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
#######una volta risolto quello che non va attacca il ruolo 
#######ansible-galaxy install geerlingguy.php
#######una volta fatta anche l'installazione
###### crea un ruolo come copia dei file dentro la cartella tmp
 

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
